### ISSUE TITLE
Connect Blog with Gitter

### ISSUE THREAD

**Issue by thejohnhoffer** [ironman5366/learn-blog#1]
After adding a Gitter integration with this repository, all collaborators can reference specific issues (like this one) from [https://gitter.im/learn-blog][0].

@ironman5366, since you administer this blog,  would you like to make this integration happen?
- Open [this page at your learn-blog][1]
- Paste the token I just emailed you

[1]: https://github.com/ironman5366/learn-blog/settings/hooks/new?service=gitter

**Comment by ironman5366** [comment]
Done!
